# -*- coding: utf-8 -*-
"""aula 01 phyton 3 semestre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17uVc5zY9WwYPBybQTCzjNlndDyjNSOXN
"""

nome = "Pedro"
print(nome)

peso = 65

altura= 1.84

def imc_pedro(peso,altura):
  imc = peso / altura**2
  return imc

imc_pedro(peso,altura)

imc_pedro(8,2)